# Generated by Django 4.1.7 on 2023-10-19 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishes",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="orderdishes",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="ratings",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="users",
            options={"managed": False},
        ),
    ]
